version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongo_api
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - transaction-api
  redis:
    container_name: redis_api
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - transaction-api
networks:
  transaction-api: