spring:
  application:
    name: financial-control
  data:
    mongodb:
      database: financial-control
      host: localhost
      port: 27017
      username: root
      password: root
      auto-index-creation: false
      authentication-database: admin
  main:
    banner-mode: off
server:
  port: 8888
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG